  - alias: The time is
    initial_state: true
    trigger:
      - platform: time
        at: '14:20:00'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.home_group
          message: "it is 2:20pm"
  - alias: Noah is Home
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.iphone
        from: 'not_home'
        to: 'home'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.home_group
          message: "Noah is home"
  - alias: Sunset Lights
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      service: scene.turn_on
      entity_id: scene.downstairs_dusk
  - alias: Goodnight Ella
    initial_state: true
    trigger:
      - platform: time
        at: '21:15:00'
    action:
      - service: scene.turn_on
        entity_id: scene.downstairs_night, scene.bedtime
      - service: tts.google_say
        data:
         entity_id: media_player.home_group
         message: "Ella, it is 9:15. Time to brush your teeth and go to bed."
  - alias: Midnight
    initial_state: true
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      - service: light.turn_off
        entity_id: group.all_lights


